name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        # run: echo "Hello, world!"
        run: echo "${{secret.SECRET_AGENT}}"
