name: Hello World Workflow

on:
  push:
    branches:
      - main
      

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: | 
           echo "Finished running tests"
           echo "Hello, world!"
           echo " The secret : ${{secrets.SECRET_AGENT}}"
           echo " value of var1 is : ${{vars.var1}} "


  push:
    branches:
      - stg
      

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: | 
           echo "Finished running tests"
           echo "I'm running on staging branch"
           echo " The secret : ${{secrets.SECRET_AGENT}}"
           echo " value of var1 is : ${{vars.var1}} "

